- dispatcher/dispatcher.go
https://github.com/renproject/lightnode/pull/11
> Merge iterator changes to Testnet

- client/client.go
This PR should help fix the "too many open files" errors that we see during stress tests. Previously, we were not closing response bodies after making a HTTP request to the Darknodes. This leaves the associated file dangling.
> Close resp body after request

- confirmer/confirmer.go
- dispatcher/dispatcher.go
Integrating #40 into `release/0.1.2`.
> Resubmit tx if Lightnode gets an error response from Darknodes

- go.mod
- go.sum
Update to use Darknode v0.1.3.
> Update to use Darknode v0.1.3

- CHANGELOG.md
- cacher/cacher_test.go
- confirmer/confirmer_test.go
- db/db.go
- db/db_test.go
- dispatcher/dispatcher_test.go
- go.mod
- go.sum
- lightnode.go
- resolver/resolver.go
- resolver/txChecker.go
- testutils/testutils.go
- Add support for queryFees method (#66)
- Add support for queryTxs method (#68)
> Release v0.1.8

- CHANGELOG.md
- updater/updater.go
- updater/updater_test.go
- Improve the logic of how lightnode update its peers
> Reduce connection time for new darknode

- confirmer/confirmer.go
This ensures Lightnodes update the status of confirming transactions if the Darknodes return a `current status = done` error upon submission.
> Update transaction if Darknodes return a "done" status

- CHANGELOG.md
- dispatcher/dispatcher.go
- dispatcher/dispatcher_test.go
- lightnode.go
- resolver/resolver.go
- store/store.go
- store/store_suite_test.go
- store/store_test.go
- testutils/darknode.go
- testutils/db.go
- testutils/http.go
- updater/updater.go
- updater/updater_test.go
- User persistent storage(database) for the `MultiAddrStore`
- Improve the p2p bootstrap logic
> Persistent DHT

- CHANGELOG.md
- store/store.go
- store/store_test.go
- updater/updater.go
- Fix an issue when trying to insert nil address list to storage. 
- Keep offline nodes in the storage to avoid unnecessary database IO.
> Fix multiAddress storage

- CHANGELOG.md
- resolver/resolver.go
- store/store.go
- store/store_test.go
- updater/updater.go
- Fixed an issue with inserting nil addresses to storage (#85)
- Update mint fees in JSON-RPC response (#93)
> Release v0.1.14

- cmd/lightnode/lightnode.go
Modify the actual config struct instead of the iterator variable
> fix(config): assign the changes to the chain config

- resolver/resolver_test.go
This PR adds test coverage to the resolver package.
> test(resolver): add unit tests for resolver

- CHANGELOG.md
- go.mod
- go.sum
- store/store.go
- store/store_test.go
- watcher/watcher_test.go
This adds a few more tests to appease coveralls.
In the process, found an error with the store's RandomBootstrapAddrs and possibly with the watcher's AddressEncodeDecode
> chore(tests): increase test coverage for store and watcher

- CHANGELOG.md
- go.mod
- go.sum
This fixes an issue with DigiByte address prefixes.
> Update Multichain to v0.2.24

- compat/v1/compat.go
- compat/v1/compat_test.go
Fixes minor issue with the shape of the queryState compat response
> fix(compat): correct queryState response shape

- .dockerignore
- .github/workflows/go.yml
- Dockerfile
- README.md
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
- Updated base image to a lighter image which reduces the image size from 1G to 300M
> Updated dockerfile to reduce image size

- cmd/localnet/main.go
- opt.go
Add localnet support so that we can test using loki
> Localnet 0.3.6

- go.mod
- go.sum
As title
--Edit: Also updates darknode version
> Bump multichain and darknode version

- watcher/watcher.go
> Remove unwanted info from watcher log

- CHANGELOG.md
- cmd/lightnode/lightnode.go
- compat/v0/compat.go
- go.mod
- go.sum
- resolver/resolver.go
- resolver/txChecker.go
- watcher/watcher.go
- watcher/watcher_test.go
- Reverts fee change
- Disables validation for fee claiming transactions
- Updates Solana gateway version
- Adds support for Avalanche
> Add support for Avalanche + small fixes

- go.mod
- go.sum
> Upgrade darknode & multichain to include Avalanche support

- watcher/watcher.go
This bumps solana to support the v0.1.3 contracts
> fix(solana): update gateway state to 0.1.3

- cacher/cacher_test.go
- cmd/lightnode/lightnode.go
- compat/v0/compat_test.go
- confirmer/confirmer_test.go
- db/db.go
- db/db_test.go
- lightnode.go
- opt.go
- resolver/resolver.go
- resolver/resolver_test.go
This PR allows the number of persisted gateways to be limited using the `MAX_GATEWAY_COUNT` env var
> fix(devtools): limit number of gateways
