rpc/client.go
rpc/client_test.go

This PR is trying to fix a bug in the `rpc/client.go` which blocks the client task from receiving new requests. There is a new test which covers the case and the old implementation fails.

Fix rpc/client

---

dispatcher/dispatcher.go

This is a hotfix for an issue which causes Darknodes to return inconsistent responses.

Use first response iterator for queries

---

cacher/cacher.go
cacher/cacher_test.go
cmd/lightnode/lightnode.go
lightnode.go

This PR introduces the concept of a `CacheLevel` which allows us to have different levels of caching within the Lightnode.
For example, the `QueryBlock` has a `CacheLevel` of `CacheLevelMin` so it only stores the response (regardless of whether it was an error or not) for a brief period of time (currently set to 3 seconds), while `SubmitTx` has a `CacheLevel` of `CacheLevelMax` which means the response gets stored (if there is no error) for an extended period of time (currently set to 24 hours).

Increase cache TTL for SubmitTx requests

---

.circleci/config.yml
cacher/cacher.go
cacher/cacher_test.go
cmd/lightnode/lightnode.go
lightnode.go
server/server_test.go

This code was previously on `beta` but that branch has been removed. Testnet Lightnode was deployed using this code over 6 weeks ago.

Improve caching and add additional input validation

---

dispatcher/dispatcher.go
dispatcher/dispatcher_test.go
lightnode.go
lightnode_test.go
store/store.go
store/store_test.go
testutils/http.go
updater/updater.go
updater/updater_test.go
validator/validator_test.go

We want to forward all requests but `queryStats` only to nodes who participate in the consensus. 
This PR pushes a simple fix which exposes a `RandomBootstrapAddresses` from the store object. 
This should be enough for current testing, but needs to be improved when we support multiple shards.

Add a new function to store to return random number of bootstrap nodes addresses

---

dispatcher/dispatcher.go
dispatcher/iterator.go
dispatcher/iterator_test.go

Currently the `firstResponseIterator` will return the first non-error response. 
If all responses are error, it will return a string which concatenates all error messages from darknodes.
This PR changes the behaviour of the `firstResponseIterator` to return the first response as long as it's a valid json.Response

Return the most returned error when using firstResponseIterator

---

cacher/cacher.go
dispatcher/dispatcher.go
http/server.go
lightnode.go
store/store.go
updater/updater.go
validator/txChecker.go
watcher/watcher.go

- Replace non-boot panics with error logs.
- Force the shift amount to be strictly greater than 10000 (for parity with Darknode).*
- Return the tx details when a user tries to submit the same tx multiple times.
- Updater will no longer remove Bootstrap nodes from the store.
- Return an internal error when something unexpected occurs.
\* A newer version of Darknode exposes these functions so Lightnode will be able to import them directly.

Improve responses, updater and error logs

---

cacher/cacher.go
confirmer/confirmer.go
dispatcher/dispatcher.go
http/server.go
lightnode.go
validator/txChecker.go

Currently, lightnode will not retry submitting txs if getting an error response. 
This PR tries to add extra retry logic if that happens. It will only mark a tx as `confirmed` in the database when getting a non-error response from the darknode.

Resubmit txs if Lightnode gets an error response from Darknodes

---

db/db.go
db/db_test.go
go.mod

This PR tries to fix of an issue reported from testnet. 
We store the details of a shiftIn tx in two tables, but we only prune one of them.
We introduce a foreign key relation between those two tables and set cascade delete. So that when the row gets deleted in the main table,  it will be removed from both of them. 
Since databases across all networks already have created those tables without the foreign key relation. We'll run the following script to update the tables. 
```sql
DELETE FROM shift_in_autogen
WHERE hash NOT IN(
SELECT hash
FROM shift_in s
WHERE s.hash = hash);
ALTER TABLE shift_in_autogen ADD foreign key (hash) references shift_in(hash) ON DELETE CASCADE;
```
> This has been tested in a testing db.

Add delete cascade to the shift_in_autogen table

---

resolver/resolver.go

This PR adds a check to the resolver for a `nil` HTTP request, as the watcher may send a message directly to the resolver when it detects a burn on the Ethereum blockchain.

Add check for nil request

---

CHANGELOG.md
cacher/cacher_test.go
dispatcher/dispatcher_test.go
go.mod
go.sum
resolver/resolver.go
testutils/http.go
testutils/testutils.go

This PR adds support for the `ren_queryShards` method in the JSON-RPC server, which allows users to query shard information.

Add support for QueryShards method

---

CHANGELOG.md
lightnode.go

Transactions now get pruned after 14 days instead of 7 days.

Increase default transaction expiry

---

CHANGELOG.md
confirmer/confirmer.go
lightnode.go
watcher/watcher.go

- Update transaction if Darknodes return a "done" status (#77)
- Increase default transaction expiry (#79)
- Print the error message for invalid burn transactions (#80)

Release v0.1.12

---

resolver/resolver_test.go
store/store.go
store/store_test.go
testutils/darknode.go

This PR allows the lightnode to query darknodes given their signatory field, instead of their multiaddr host value

fix(store): index multiaddrs by signatory

---

CHANGELOG.md
Dockerfile

This should fix the docker build issues that have been reported with filecoin-ffi not being available.

fix(docker): allow building without submodule

---

CHANGELOG.md
Dockerfile
watcher/watcher.go

This PR updates the Lightnode watcher to only process new event logs. This is generally the case, unless there are issues with the underlying blockchain node that result in a resync. Processing old events if generally not an issue as the Lightnode will drop transactions if it detects they have already ben handled by the Darknode, however if the transaction backlog builds up substantially (in the case of a resync, for example), it can cause the Lightnode to be rate limited by the Darknodes upon dispatching requests.

Ensure watcher does not process old events

---

compat/v0/compat.go
go.mod
go.sum
resolver/resolver_test.go

This addresses the PR issue of supporting burn tx querying (required for the release flow which wasn't tested previously)
Also includes a fix for reverted mint txes, to include the revert reason in the response.

fix(compat): query v0 burn tx and reverted mint tx

---

compat/v0/compat.go
compat/v0/compat_test.go
compat/v0/rpc.go
resolver/resolver.go
testutils/testutils.go

This adds support for the v2 queryFees RPC, which is needed for the legacy UI's to keep working as expected

feat(compat): v0 query fees support

---

compat/v0/store.go
go.mod
go.sum
lightnode.go
watcher/watcher.go
watcher/watcher_test.go

This PR increases watcher test coverage, by allowing us to mock the fetching of burn event logs

chore(watcher): test burn log handling via mock

---

CHANGELOG.md
cmd/lightnode/lightnode.go
lightnode.go
opt.go
watcher/watcher.go
watcher/watcher_test.go

This adds two flags to the watcher, to prevent over-subscribing to event logs via a configurable limit, and to prevent fetching the latest blocks to avoid re-shuffling and missing events in the latest blocks.

fix(watcher): maxBlockAdvance and confidenceInterval 

---

CHANGELOG.md
dispatcher/dispatcher.go
resolver/resolver.go
store/store.go
store/store_test.go
testutils/darknode.go
testutils/db.go
testutils/http.go
updater/updater.go
updater/updater_test.go

- Adding an in-mem cache layer to the address store for fast read/write.
- When updating the address store, it will send `queryPeers` to 50 random peers and collect the result. If we get multiple multiaddress for the same ID, we will ping all of them to see which one is actually online. 
- There's still a small chance we get the incorrect multiAddress (If all 50 random peers return the wrong multiAddress for that ID). I'm open for suggestions.
Instructions 
- We need to drop the old `address` table when deploying this change as the table structure has changed
```sql
DROP TABLE addresses
```

Fix updater logic to store latest darknode multiAddress

---

cmd/lightnode/lightnode.go
lightnode.go
watcher/watcher.go

Currently, the lightnode will create a watcher for every token supported by a chain's registry.
This is not desirable, because the darknode may not support every token in the registry.
This PR addresses that by filtering watcher creation based on the whitelist provided by the darknode.

fix(watcher): only watch whitelisted selectors

---

watcher/watcher.go

Currently, if a sourcechain RPC node is down when a burn is detected, we will skip persisting the burn request and have to submit it manually after recovering.
This PR makes the lightnode retry until the valid burn request is processed, or until the blockheight is manually increased in case of a an invalid burn slipping through

fix(watcher): retry when burn submission fails

---

confirmer/confirmer.go

Currently, we log an error when a submission of an unconfirmed tx happens.
This should not be the case, as a lack of confirmations is expected.

fix(confirmer): don't log insufficient confirmations as error

---

confirmer/confirmer.go

The previous PR (#138) missed a case for account-based chains.

fix: prevent logging for insufficient confs error

---

watcher/watcher.go

This logic was previously fine when Darknode only supported chains with 8 decimal places, however now can result in an overflow. This has already been fixed on v0.4.0.

Fix watcher amount overflow

---

watcher/watcher.go

The `fetcher` will block until the context is done(after 15s) and won't iterate to the next event. 
```goalng
select{
case <-ctx.Done():
}
```
To fix that, we need to add a `default` case for the select statement. 
Also, we return an error if the deadline exceeds because there might be burns we haven't handle before the deadline and we want to check the events again.

Fix log fetcher would miss burns 

---

resolver/resolver.go

Currently, when querying intrinsics (such as `System/epoch`) Lightnode returns the `executing` status as there is no output populated. This PR updates the Lightnode to only return the `executing` status for extrinsic transactions.

Fix stuck executing transactions

---

confirmer/confirmer.go

This reduces error logs for expected insufficient confirmations errors

fix(confirmer): reduce error logs for confirmations

---

CHANGELOG.md
go.mod
go.sum

This PR updates the lightnode to use the commit containing some fixes for fantom integration.

update darknode dependency

---

.github/workflows/go.yml

This PR adds a `DUMMY_MINT_AND_BURN` variable to the environment, that enables the dummy mints and burns in the ren-solana docker image. Refer: https://github.com/renproject/ren-solana/blob/cfa3c3ab9394e56b2b2b8c21fc925370dd4ecdaa/deploy.sh#L67

enable dummy mint and burn (based on new deploy script)

---

watcher/watcher.go
watcher/watcher_test.go

We changed how we handle the 1 indexed solana burns in 151; but did not update the uninitialized burns case; this fixes that

fix(watcher): don't decrement latest block when instantiating

---

.github/workflows/go.yml
watcher/watcher.go
watcher/watcher_test.go

This PR moves chain specific logic in `burnToParams` to separate methods. This solves the issue of all destination addresses being treated as base58 encoded for Solana. This also moves the burn detection log to `burnToParams` so that it logs the address only after it has been properly encoded

Fix destination adrress encoding/decoding while building transaction

---

go.mod
go.sum
lightnode.go
resolver/txChecker.go

In v0.4.2, RenVM burn validation involves checking the burned amount does not exceed the tracked minted amount. This is the first time RenVM needs to access the block state to validate a cross-chain transaction. Hence, we must now pass the contract state when utilising the cross-chain validation function inside Lightnode. Since the Lightnode does not keep track of the latest block state, we pass a zeroed state with the "tracked minted amount" set to `MaxU256` for each host chain. This essentially means that Lightnode will not perform any validation for ensuring the burn amount is below the threshold.

Initialise minted amount

---

CHANGELOG.md
compat/v0/compat.go

In v0.4.2, cross-chain fees are now tracked inside the RenVM block state. This PR updates Lightnode to use these values for v0 compatibility instead of the hard-coded values.

Pull cross-chain fees from RenVM state

---

compat/v0/compat.go
db/db.go
db/db_test.go
go.mod
go.sum
resolver/resolver.go

Requires https://github.com/renproject/darknode/pull/433
This allows for the latest txs to be queried via the "latest" parameter in QuertTxs

feat(resolver): order txs by timestamp in querytxs

---

cmd/lightnode/lightnode.go
compat/v0/compat.go
compat/v0/compat_test.go
go.mod
resolver/resolver.go
resolver/resolver_test.go
resolver/txChecker.go
resolver/validator.go

The changes to the compat layer to support end to end burn support (vs relying on the watcher) didn't correctly implement v0 hashing, resulting in incorrect selectors & gateways. This PR reverts some of the changes to get mint compatibility working again

fix(compat): v0 tx submission

---

compat/v0/store.go

Currenntly, tx hashes are being stored in base64 format instead of base64url format in some places, this allows us to handle both formats

fix(compat): decode plain base64 hash as well
